algorithm: uda_lossnet
save_dir: ./saved_models/cifar10_uda
save_name: b_uda_lossnet_cifar10_wrn_28_2_1000_lr0.01_True_bsz100_sym_0.2_False_10000_1000_feat_expno1N_uni_-1_11
resume: False
load_path: ./saved_models/cifar10_uda/b_uda_lossnet_cifar10_wrn_28_2_1000_lr0.01_True_bsz100_sym_0.2_False_10000_1000_feat_expno1N_uni_-1_11/latest_model.pth
overwrite: True
use_tensorboard: True
epoch: 2
num_train_iter: 30000
num_eval_iter: 128
num_labels: 1000
batch_size: 100
eval_batch_size: 256
ema_m: 0.999
crop_ratio: 0.875
img_size: 32
optim: SGD
lr: 0.01
momentum: 0.9
weight_decay: 0.0001
layer_decay: 1.0
amp: False
clip: 0.0
use_cat: True
net: wrn_28_2
net_from_name: False
data_dir: ./data
dataset: cifar10
train_sampler: RandomSampler
num_classes: 10
num_workers: 1
seed: 11
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:10001
dist_backend: nccl
gpu: None
s_it: -1
steplr: True
noise_type: sym
noise_ratio: 0.2
weak_only: False
eval_set_size: 10000
e_batch_size: 1000
meta_goal: feat_expno1N
w_f: uni
threshold: 0
use_pretrain: False
renew: None
