algorithm: fixmatch_lossnet
save_dir: ./saved_models/cifar100
save_name: b_0.1_fixmatch_lossnet_cifar100_resnet50_10000_lr0.03_True_bsz100_human_0_False_1000_500_feat_expno1N_uni_1e-05_beta0_15
resume: False
load_path: ./saved_models/cifar100/b_0.1_fixmatch_lossnet_cifar100_resnet50_10000_lr0.03_True_bsz100_human_0_False_1000_500_feat_expno1N_uni_1e-05_beta0_15/latest_model.pth
overwrite: True
use_tensorboard: True
epoch: 1000
num_train_iter: 30000
num_eval_iter: 512
num_labels: 10000
batch_size: 100
eval_batch_size: 256
hard_label: True
T: 0.5
p_cutoff: 0.95
ulb_loss_ratio: 1.0
uratio: 7
ema_m: 0.999
crop_ratio: 0.875
img_size: 32
optim: SGD
lr: 0.03
momentum: 0.9
weight_decay: 0.0001
layer_decay: 1.0
amp: False
clip: 0.0
use_cat: True
net: resnet50
net_from_name: False
data_dir: ./data
dataset: cifar100
train_sampler: RandomSampler
num_classes: 100
num_workers: 1
seed: 15
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:10010
dist_backend: nccl
gpu: None
beta: 0
steplr: True
noise_type: human
noise_ratio: 0
weak_only: False
eval_set_size: 1000
e_batch_size: 500
meta_goal: feat_expno1N
w_f: uni
threshold: 0.1
use_pretrain: False
renew: None
meta_lr: 1e-05
