algorithm: fixmatch_lossnet
save_dir: ./saved_models/cifar10
save_name: b_0.1_fixmatch_lossnet_cifar10_wrn_28_2_4000_lr0.03_True_bsz100_human_worst_0_False_1000_1000_clid_uni_1e-05_beta0_8
resume: False
load_path: ./saved_models/cifar10/b_0.1_fixmatch_lossnet_cifar10_wrn_28_2_4000_lr0.03_True_bsz100_human_worst_0_False_1000_1000_clid_uni_1e-05_beta0_8/latest_model.pth
overwrite: True
use_tensorboard: True
epoch: 1000
num_train_iter: 30000
num_eval_iter: 512
num_labels: 4000
batch_size: 100
eval_batch_size: 256
hard_label: True
T: 0.5
p_cutoff: 0.95
ulb_loss_ratio: 1.0
uratio: 7
ema_m: 0.999
crop_ratio: 0.875
img_size: 32
optim: SGD
lr: 0.03
momentum: 0.9
weight_decay: 0.0001
layer_decay: 1.0
amp: False
clip: 0.0
use_cat: True
net: wrn_28_2
net_from_name: False
data_dir: ./data
dataset: cifar10
train_sampler: RandomSampler
num_classes: 10
num_workers: 1
seed: 8
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:10008
dist_backend: nccl
gpu: None
beta: 0
steplr: True
noise_type: human_worst
noise_ratio: 0
weak_only: False
eval_set_size: 1000
e_batch_size: 1000
meta_goal: clid
w_f: uni
threshold: 0.1
use_pretrain: False
renew: None
meta_lr: 1e-05
