algorithm: fullysupervised_lossnet
save_dir: ./saved_models/cifar10_uda
save_name: b_fullysupervised_lossnet_clothing1m_resnet50_192000_lr0.005_True_bsz32_human_0_False_7000_100_feat_expno1N_uni_1e-05_beta0_2
resume: False
load_path: ./saved_models/cifar10_uda/b_fullysupervised_lossnet_clothing1m_resnet50_192000_lr0.005_True_bsz32_human_0_False_7000_100_feat_expno1N_uni_1e-05_beta0_2/latest_model.pth
overwrite: True
use_tensorboard: True
epoch: 10
num_train_iter: 60000
num_eval_iter: 1000
num_labels: 192000
batch_size: 32
eval_batch_size: 256
ema_m: 0.999
crop_ratio: 0.875
img_size: 256
optim: SGD
lr: 0.005
momentum: 0.9
weight_decay: 0.0001
layer_decay: 1.0
amp: False
clip: 0.0
use_cat: True
net: resnet50
net_from_name: False
data_dir: ./data
dataset: clothing1m
train_sampler: RandomSampler
num_classes: 14
num_workers: 1
seed: 2
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:10001
dist_backend: nccl
gpu: None
beta: 0
steplr: True
noise_type: human
noise_ratio: 0
weak_only: False
eval_set_size: 7000
e_batch_size: 100
meta_goal: feat_expno1N
w_f: uni
threshold: 0
use_pretrain: False
renew: None
meta_lr: 1e-05
