algorithm: fullysupervised_lossnet
save_dir: ./saved_models/cifar10_uda
save_name: b_fullysupervised_lossnet_cifar100_wrn_28_10_50000_lr0.1_True_bsz128_sym_0.6_False_1000_100_cer_uni_0.001_beta0_13
resume: False
load_path: ./saved_models/cifar10_uda/b_fullysupervised_lossnet_cifar100_wrn_28_10_50000_lr0.1_True_bsz128_sym_0.6_False_1000_100_cer_uni_0.001_beta0_13/latest_model.pth
overwrite: True
use_tensorboard: True
epoch: 200
num_train_iter: 20000
num_eval_iter: 512
num_labels: 50000
batch_size: 128
eval_batch_size: 256
ema_m: 0.999
crop_ratio: 0.875
img_size: 32
optim: SGD
lr: 0.1
momentum: 0.9
weight_decay: 0.0001
layer_decay: 1.0
amp: False
clip: 0.0
use_cat: True
net: wrn_28_10
net_from_name: False
data_dir: ./data
dataset: cifar100
train_sampler: RandomSampler
num_classes: 100
num_workers: 1
seed: 13
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:10005
dist_backend: nccl
gpu: None
beta: 0
steplr: True
noise_type: sym
noise_ratio: 0.6
weak_only: False
eval_set_size: 1000
e_batch_size: 100
meta_goal: cer
w_f: uni
threshold: 0
use_pretrain: False
renew: None
meta_lr: 0.001
